name: Get changed files

on:
  pull_request

jobs:
  getChangedFiles:
    runs-on: ubuntu-latest
    steps:
      - name: Get changed files
        uses: jitterbit/get-changed-files@v1
        id: files
        with:
          format: 'csv'
      - run: |
          mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
          for added_modified_file in "${added_modified_files[@]}"; do
            echo "Do something with this ${added_modified_file}."
          done
          echo "size = ${#added_modified_files[@]}"
