name: Get changed files

on:
  pull_request

jobs:
  getChangedFiles:
    runs-on: ubuntu-latest
    steps:
      - name: Get changed files
        uses: jitterbit/get-changed-files@v1
        id: files
        with:
          format: 'csv'
      - run: |
          mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
          for added_modified_file in "${added_modified_files[@]}"; do
            echo "Do something with this ${added_modified_file}."
            if [[ ${added_modified_file} =~ ^([1-9]{2}).+\.[a-z]{2}$ ]]; then
              echo "problem_no=${BASH_REMATCH[1]}" >> $GITHUB_ENV
            fi
          done
          echo "size = ${#added_modified_files[@]}"
          echo "action_state=yellow" >> $GITHUB_ENV
      - run: |
          echo "${{ env.action_state }}"
          echo "${{ env.problem_no }}"
      - name: Post a message with the remaining problems
        if: env.problem_no
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            Nice work, problem [#${{env.problem_no}}](https://projecteuler.net/problem=${{env.problem_no}) solved! 👨‍💻 ✅

          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'

