name: Pull request sorter

on:
  pull_request:
    branches: [ master ]

jobs:
  addLabels:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@main
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        yaml-file: .github/labeler.yml