name: Test conditional flows

on:
  pull_request

jobs:
  testFlow:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for build to suceed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: test
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: addLabels
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Do something if a new label is added
        if: steps.test.outputs.conclusion == 'success' && contains(github.event.pull_request.labels.*.name, 'nestedDir')
        run: echo Hello, world! 

      - name: Run a one-line script
        run: echo Hello, world!
